export interface ModelInfo {
  id: string;
  name: string;
  provider: 'OpenAI' | 'DeepSeek' | 'Google' | 'Alibaba' | 'Meta';
  kind: 'chat' | 'embedding';
  category: 'Writing & Logic' | 'Fast & Economical' | 'Long Documents' | 'Coding & Math' | 'Chinese & Multilingual' | 'Embeddings';
  description: string;
  recommendedFor: string;
  badgeColor: string;
}

export const SUPPORTED_MODELS: ModelInfo[] = [
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'OpenAI',
    kind: 'chat',
    category: 'Writing & Logic',
    description: 'Premier all-around model with high reliability, great for essays, critiques, and complex research.',
    recommendedFor: 'Academic writing, literature review, general Q&A',
    badgeColor: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
  },
  {
    id: 'gpt-5',
    name: 'GPT-5',
    provider: 'OpenAI',
    kind: 'chat',
    category: 'Writing & Logic',
    description: 'Next-generation flagship model with deep context understanding and creative synthesis.',
    recommendedFor: 'Complex problem solving, advanced analysis',
    badgeColor: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    provider: 'OpenAI',
    kind: 'chat',
    category: 'Fast & Economical',
    description: 'Lightweight, rapid-response model optimized for speed while saving your quota.',
    recommendedFor: 'Quick definitions, proofreading, idea generation',
    badgeColor: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    provider: 'DeepSeek',
    kind: 'chat',
    category: 'Fast & Economical',
    description: 'Blazing fast responses with impressive programming and analytical abilities.',
    recommendedFor: 'Coding help, rapid brainstorm, quick translations',
    badgeColor: 'bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-300 border-blue-200 dark:border-blue-800',
  },
  {
    id: 'deepSeek-V4-Pro-hkbu',
    name: 'DeepSeek V4 Pro',
    provider: 'DeepSeek',
    kind: 'chat',
    category: 'Coding & Math',
    description: 'High-capability model tailored for STEM, rigorous mathematics, and software engineering.',
    recommendedFor: 'Python scripts, data structures, quantitative homework',
    badgeColor: 'bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-300 border-blue-200 dark:border-blue-800',
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    kind: 'chat',
    category: 'Long Documents',
    description: 'Massive context window that can digest entire books, lengthy research papers, and large codebases.',
    recommendedFor: 'Summarizing 50+ page PDFs, synthesis across multiple sources',
    badgeColor: 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300 border-amber-200 dark:border-amber-800',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    kind: 'chat',
    category: 'Fast & Economical',
    description: 'Fast multimodal powerhouse with rapid summarization and multilingual chat.',
    recommendedFor: 'Quick reading, document queries, flash summaries',
    badgeColor: 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300 border-amber-200 dark:border-amber-800',
  },
  {
    id: 'qwen3-max',
    name: 'Qwen 3 Max',
    provider: 'Alibaba',
    kind: 'chat',
    category: 'Chinese & Multilingual',
    description: 'Industry-leading performance in Traditional/Simplified Chinese, idioms, and local cultural contexts.',
    recommendedFor: 'Chinese essays, translation, local HK/China cultural context',
    badgeColor: 'bg-purple-100 text-purple-800 dark:bg-purple-950 dark:text-purple-300 border-purple-200 dark:border-purple-800',
  },
  {
    id: 'qwen-plus',
    name: 'Qwen Plus',
    provider: 'Alibaba',
    kind: 'chat',
    category: 'Chinese & Multilingual',
    description: 'Quick and fluent bilingual model balancing quality and speed for everyday Chinese tasks.',
    recommendedFor: 'Bilingual chat, grammar checks, conversational practice',
    badgeColor: 'bg-purple-100 text-purple-800 dark:bg-purple-950 dark:text-purple-300 border-purple-200 dark:border-purple-800',
  },
  {
    id: 'o1',
    name: 'OpenAI o1',
    provider: 'OpenAI',
    kind: 'chat',
    category: 'Writing & Logic',
    description: 'Chain-of-thought reasoning model that spends deliberate time thinking before delivering deep analysis.',
    recommendedFor: 'Complex logic puzzles, proof checking, philosophy arguments',
    badgeColor: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
  },
  {
    id: 'o3-mini',
    name: 'OpenAI o3-mini',
    provider: 'OpenAI',
    kind: 'chat',
    category: 'Coding & Math',
    description: 'High-speed reasoning model specialized in math, logic, and programmatic thinking.',
    recommendedFor: 'Math steps, statistics, algorithmic reasoning',
    badgeColor: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
  },
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'Meta',
    kind: 'chat',
    category: 'Writing & Logic',
    description: 'Meta’s open-weights model fine-tuned for high-quality instruction adherence and friendly conversation.',
    recommendedFor: 'General creative writing, conversational agents',
    badgeColor: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-950 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800',
  },
  {
    id: 'text-embedding-3-small',
    name: 'Text Embedding 3 Small',
    provider: 'OpenAI',
    kind: 'embedding',
    category: 'Embeddings',
    description: 'Compact, efficient vector embeddings for search and document indexing.',
    recommendedFor: 'RAG knowledge bases, semantic search',
    badgeColor: 'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-300 border-slate-200 dark:border-slate-700',
  },
  {
    id: 'text-embedding-3-large',
    name: 'Text Embedding 3 Large',
    provider: 'OpenAI',
    kind: 'embedding',
    category: 'Embeddings',
    description: 'High-accuracy vector representations for deep semantic clustering and retrieval.',
    recommendedFor: 'Advanced information retrieval, multi-document RAG',
    badgeColor: 'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-300 border-slate-200 dark:border-slate-700',
  },
];
